#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PERF_DIR="${ROOT_DIR}/perf"

DEB_PATH=$(ls "${ROOT_DIR}"/target/debian/exfilguard_*.deb 2>/dev/null || true)
if [ -z "${DEB_PATH}" ]; then
  echo "ERROR: build the deb first (see packaging/deb-container) so target/debian/exfilguard_*.deb exists."
  exit 1
fi

cd "${PERF_DIR}"
docker compose build exfilguard
docker compose up --abort-on-container-exit --exit-code-from client exfilguard upstream client
docker compose down

echo "HTML report is generated by k6 to perf/results/summary.html via handleSummary()"
